apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: production
spec:
  destination:
    namespace: default
    server: https://101.44.32.101:5443
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/codefresh-hosted/*.yaml,runtimes/codefresh-hosted/**/*.yaml,codefresh-hosted-managed-cluster-production-cm.yaml}
      recurse: true
    path: resources
    repoURL: >-
      https://github.com/trc-sdlc-huawei/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
